santivaldi/santivaldi/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='IniciarSesion'),
    #cliente
    path('', views.index, name='index'),
    path('panaderia', views.panaderia),
    path('reposteria', views.reposteria),
    path('abarrotes', views.abarrotes),
    path('formulario', views.realizar_pedidos, name='pedido'),

    #Autentificacion
    path('IniciarSesion', views.iniciarSesion, name="inicio_sesion"),
    path('CerrarSesion', views.cerrarSesion),
    
    # JEFE
    path('registrar_trabajador', login_required(views.registrar_trabajador), name="registro"),
    path('trabajadores',login_required(views.ver_trabajadores),name='trabajador'),
    path('eliminar_trabajador/<rut>/', login_required(views.eliminar_trabajador), name="eliminar_trab"),
    path('modificar_trabajador/<rut>/', login_required(views.modificar_trabajador),name="modificar_trab"),
    path('detalle_producto', login_required(views.admin_productos)),

    #Administrador
    path('ingresar_producto', login_required(views.ingresar_producto)),
    path('productos', login_required(views.productos), name='productos_opciones'),
    path('eliminar_producto/<id>/', login_required(views.eliminar_producto), name="eliminar_prod"),
    path('modificar_producto/<id>/', login_required(views.modificar_producto),name="modificar_prod"),
    
    #vendedor
    path('ver_pedidos', login_required(views.ver_pedidos), name='pedidos'),
    path('ver_stock', login_required(views.stock)),
    path('modificar_estado/<id>/', login_required(views.modificar_estado), name="modificar_estados") ,

    
   


    
    
]
if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


santivaldi/app/models.py
from django.db import models
import os
from django.contrib.auth.models import User
from django.utils import timezone
import random
from datetime import timedelta
# Create your models here.

def get_upload_path(instance, filename):
    # Obtener la categoría del producto
    categoria = instance.categoria
    # Crear la ruta de almacenamiento basada en la categoría
    return os.path.join("productos", categoria, filename)

class Producto(models.Model):
    CATEGORIAS_CHOICES = [
        ('reposteria', 'Reposteria'),
        ('panaderia', 'Panadería'),
        ('abarrotes', 'Abarrotes'),
    ]

    idproducto = models.AutoField(primary_key=True)
    nombre_producto = models.CharField(max_length=45, blank=True, null=True)
    precio = models.IntegerField(blank=True, null=True)
    imagen = models.ImageField(upload_to=get_upload_path, null=True)
    categoria = models.CharField(max_length=20, choices=CATEGORIAS_CHOICES)
    stock = models.IntegerField(blank=True, null=True)
    fecha_ingreso = models.DateTimeField(default=timezone.now)
    fecha_vencimiento = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.nombre_producto

    def generar_fecha_vencimiento(self):
        # Generar un número de meses al azar (entre 1 y 12)
        meses_al_azar = random.randint(1, 12)

        # Calcular la nueva fecha de vencimiento sumando meses al actual
        nueva_fecha_vencimiento = self.fecha_ingreso + timedelta(days=30 * meses_al_azar)

        return nueva_fecha_vencimiento

    def save(self, *args, **kwargs):
        # Si la fecha de vencimiento no se estableció, generamos una al guardar el producto
        if not self.fecha_vencimiento:
            self.fecha_vencimiento = self.generar_fecha_vencimiento()

        super().save(*args, **kwargs)
    

class Trabajador (models.Model):
    categorias_choices = [
        ('Administrador', 'administrador'),
        ('Vendedor', 'vendedor'),
        
    ]
    rut = models.CharField(max_length=12, primary_key=True)
    nombre_trabajador = models.CharField(max_length=25, blank=True, null=True)
    apellido_trabajador = models.CharField(max_length=25, blank=True, null=True)
    email_trabajador = models.CharField(max_length=100, blank=True, null=True)
    telefono_trabajador = models.CharField(max_length=9,blank=True, null=True)
    rol = models.CharField(max_length=20, choices=categorias_choices)
    contraseña = models.CharField(max_length=255, default='')
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self) -> str:
        return self.nombre_trabajador
    

class Formulario(models.Model):
    ESTADO_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('en_proceso', 'En Proceso'),
        ('completo', 'Completo'),
    ]

    id_formulario = models.AutoField(primary_key=True)
    nombre_cliente = models.CharField(max_length=25, blank=True, null=True)
    apellido_cliente = models.CharField(max_length=25, blank=True, null=True)
    telefono_cliente = models.CharField(max_length=9, blank=True, null=True)    
    pedido = models.CharField(max_length=450, blank=True, null=True)
    estado = models.CharField(max_length=20, blank=True, null=True,choices=ESTADO_CHOICES, default='pendiente')

    def __str__(self):
        return f'Formulario-{self.id_formulario} ({self.nombre_cliente} {self.apellido_cliente})'


santivaldi/templates/administrador/ingresar_producto.html
{% extends 'app/index.html' %}
{%load static%}




{% block titulo %}
<h1 class="heading-1">Ingresar Productos</h1>
{%endblock%}
{% block section %}
{%endblock%}

{% block contenido %}
<form method="post" enctype="multipart/form-data" style="max-width: 400px; margin: auto;">
    {% csrf_token %}
    <div class="form-container">
        <div class="form-group">
            <label for="{{ form.nombre_producto.id_for_label }}">Nombre del Producto:</label>
            <div class="texto">{{ form.nombre_producto }}</div>
            {{ form.nombre_producto.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.precio.id_for_label }}">Precio:</label>
            <div class="texto">{{ form.precio }}</div>
            {{ form.precio.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.imagen.id_for_label }}">Imagen:</label>
            <div class="texto">{{ form.imagen }}</div>
            {{ form.imagen.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.categoria.id_for_label }}">Categoría:</label>
            <div class="texto"></div>{{ form.categoria }}</div>
            {{ form.categoria.errors }}
        </div>

        <div class="form-group">
            <label class="label" for="{{ form.stock.id_for_label }}">Stock:</label>
            <div class="texto">{{ form.stock }}</div>
            {{ form.stock.errors }}
        </div>
        <div class="form-group">
            <label class="label" for="{{ form.fecha_vencimiento.id_for_label }}">Fecha de vencimiento:</label>
            <div class="texto">{{ form.fecha_vencimiento }}</div>
            {{ form.fecha_vencimiento.errors }}
        </div>
    </div>

    <button class="texto" type="submit" style="display: block; margin: auto;">Guardar Producto</button>
</form>

<style>
    form {
        max-width: 400px;
        margin: auto;
        padding: 15px;
        box-sizing: border-box;
    }
    .texto{
        font-size: 16px;
    }
    .form-group {
        margin-bottom: 15px;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        box-sizing: border-box;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    #id_categoria {
        font-size: 16px; /* Ajusta el tamaño de la fuente */
        padding: 5px; /* Ajusta el relleno */
        width: 100%; /* Ajusta el ancho del cuadro desplegable */
    }
</style>

{% endblock %}

{% block contenido2 %}
{% endblock %}

santivaldi/templates/administrador/modificar_producto.html
{% extends 'app/index.html' %}
{%load static%}


{% block titulo %}
<h1 class="heading-1">Modificar Producto - {{ producto.nombre_producto }}</h1>
{%endblock%}





{% block contenido %}

<form method="post" enctype="multipart/form-data" style="max-width: 400px; margin: auto;">
    {% csrf_token %}
    <div class="form-container">
        <div class="form-group">
            <label for="{{ form.nombre_producto.id_for_label }}">Nombre del Producto:</label>
            <div class="texto">{{ form.nombre_producto }}</div>
            {{ form.nombre_producto.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.precio.id_for_label }}">Precio:</label>
            <div class="texto">{{ form.precio }}</div>
            {{ form.precio.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.imagen.id_for_label }}">Imagen:</label>
            <div class="texto">{{ form.imagen }}</div>
            {{ form.imagen.errors }}
        </div>

        <div class="form-group">
            <label for="{{ form.categoria.id_for_label }}">Categoría:</label>
            <div class="texto"></div>{{ form.categoria }}</div>
            {{ form.categoria.errors }}
        </div>

        <div class="form-group">
            <label class="label" for="{{ form.stock.id_for_label }}">Stock:</label>
            <div class="texto">{{ form.stock }}</div>
            {{ form.stock.errors }}
        </div>
        <div class="form-group">
            <label class="label" for="{{ form.fecha_vencimiento.id_for_label }}">Fecha de vencimiento:</label>
            <div class="texto">{{ form.fecha_vencimiento }}</div>
            {{ form.fecha_vencimiento.errors }}
        </div>
    </div>

    <button type="submit" style="display: block; margin: auto;">Guardar Producto</button>
</form>

<style>
    form {
        max-width: 400px;
        margin: auto;
        padding: 15px;
        box-sizing: border-box;
    }
    .texto{
        font-size: 16px;
    }
    .form-group {
        margin-bottom: 15px;
    }

    button {
        display: block;
        width: 100%;
        padding: 10px;
        box-sizing: border-box;
        background-color: #4CAF50;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
    #id_categoria {
        font-size: 16px; /* Ajusta el tamaño de la fuente */
        padding: 5px; /* Ajusta el relleno */
        width: 100%; /* Ajusta el ancho del cuadro desplegable */
    }
</style>
{% endblock %}

{% block contenido2 %}
{% endblock %}

santivaldi/templates/administrador/opcion_productos.html
{% extends 'app/index.html' %}
{%load static%}


{% block titulo %}

{%endblock%}
{% block section %}
{%endblock%}


{% block contenido %}
{% load humanize%}

<div class="container mt-5">
    <div class="row">
        <h2 style=" justify-content: center;">Abarrotes</h2>
    </div>
    {% if app_producto %}
    <div class="table-responsive"> <!-- Add this div -->
        <table class="table">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>Stock</td>
                    <td>Precio</td>
                    <td>Ingresado</td>
                    <td>Opciones</td>
    
                </tr>
            </thead>
            <tbody>
                {% for prod in app_producto %}
                {% if prod.categoria == "abarrotes" or prod.categoria == "Abarrotes" %} 
                <tr>
                    <td>{{ prod.nombre_producto }}</td>
                    <td>(Unidad): {{ prod.stock}}</td>
                    <td>${{ prod.precio|intcomma}}</td>
                    <td>{{ prod.fecha_ingreso  }}</td>
                    <td><a href="{% url 'modificar_prod' prod.idproducto %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'eliminar_prod' prod.idproducto %}" class="btn btn-danger">Eliminar</a></td>

                </tr>
                {% endif %}
                {% endfor %}

            </tbody>
        </table>
    </div> <!-- Close the div -->
    {% else %}
    <div class="col-md-12">
        <p style="font-size: 16px;">No hay Productos ingresados.</p>
    </div>
  
    {% endif %}
</div>


<div class="container mt-5">
    <div class="row">
        <h2 style=" justify-content: center;">Repostería</h2>
    </div>
    {% if app_producto %}
    <div class="table-responsive"> <!-- Add this div -->
        <table class="table">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>Stock</td>
                    <td>Precio</td>
                    <td>Ingresado</td>
                    <td>Opciones</td>
    
                </tr>
            </thead>
            <tbody>
                {% for prod in app_producto %}
                {% if prod.categoria == "reposteria" or prod.categoria == "Reposteria" %}

                <tr>
                    <td>{{ prod.nombre_producto }}</td>
                    <td>(Unidad): {{ prod.stock}}</td>
                    <td>${{ prod.precio|intcomma}}</td>
                    <td>{{ prod.fecha_ingreso  }}</td>
                    <td><a href="{% url 'modificar_prod' prod.idproducto %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'eliminar_prod' prod.idproducto %}" class="btn btn-danger">Eliminar</a></td>

                </tr>
                {% endif %}
                {% endfor %}

            </tbody>
        </table>
    </div> <!-- Close the div -->
    {% else %}
    <div class="col-md-12">
        <p style="font-size: 16px;">No hay Productos ingresados.</p>
    </div>
  
    {% endif %}
</div>


<div class="container mt-5">
    <div class="row">
        <h2 style=" justify-content: center;">Panadería</h2>
    </div>
    {% if app_producto %}
    <div class="table-responsive"> <!-- Add this div -->
        <table class="table">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>Stock</td>
                    <td>Precio</td>
                    <td>Ingresado</td>
                    <td>Opciones</td>
    
                </tr>
            </thead>
            <tbody>
                {% for prod in app_producto %}
                {% if prod.categoria == "panaderia" or prod.categoria == "Panadería" %}
                <tr>
                    <td>{{ prod.nombre_producto }}</td>
                    <td>(KG): {{ prod.stock}}</td>
                    <td>${{ prod.precio|intcomma}}</td>
                    <td>{{ prod.fecha_ingreso  }}</td>
                    <td><a href="{% url 'modificar_prod' prod.idproducto %}" class="btn btn-primary">Modificar</a>
                        <a href="{% url 'eliminar_prod' prod.idproducto %}" class="btn btn-danger">Eliminar</a></td>

                </tr>
                {% endif %}
                {% endfor %}

            </tbody>
        </table>
    </div> <!-- Close the div -->
    {% else %}
    <div class="col-md-12">
        <p style="font-size: 16px;">No hay Productos ingresados.</p>
    </div>
  
    {% endif %}
</div>


<style>
    table {
        width: 100%; /* Change this to 100% */
        margin: auto;
        border-collapse: collapse;
        font-size: 20px;
    }

    th, td {
        border: 2px solid #dddddd;
        text-align: left;
        padding: 10px;
    }

    th {
        background-color: #f2f2f2;
    }

    .btn {
        padding: 12px;
        text-decoration: none;
        color: white;
    }

    .btn-danger {
        background-color: #ff0000;
    }
</style>
{% endblock %}

{% block contenido2 %}
{% endblock %}